global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

# ADD THIS ENTIRE 'alerting' SECTION
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093' # Use service name and Alertmanager's internal port

scrape_configs:
  # Job to scrape our Flask application's internal metrics
  - job_name: 'sre-flask-app'
    static_configs:
      - targets: ['app:5000']

  # Job to scrape the Node Exporter for machine metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Job to use the Blackbox Exporter to probe our app
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://app:5000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115