# k8s/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sre-app-hpa  # Name of your HPA object
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-app-deployment # This MUST match the name of your Deployment
  minReplicas: 1            # Minimum number of pods
  maxReplicas: 5            # Maximum number of pods to scale out to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Target 50% CPU utilization of the requested CPU for each pod.
        # This means if a pod's CPU usage goes above 50% of its requested CPU (e.g., above 50m if request is 100m),
        # the HPA will try to scale up.
        averageUtilization: 50